{{- if .Values.serviceExt.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: icp-alb-svc
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingressIcp.annotations.acmCertificateArn | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingressIcp.annotations.listenPorts | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingressIcp.annotations.sslRedirect | quote }}
    alb.ingress.kubernetes.io/load-balancer-attributes: {{ .Values.ingressIcp.annotations.loadBalancerAttributes | quote }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingressIcp.annotations.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingressIcp.annotations.targetType | quote }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.ingressIcp.annotations.backendProtocol | quote }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingressIcp.annotations.subnetAllowList | quote }}
    alb.ingress.kubernetes.io/success-codes: 200-302

spec:
  type: LoadBalancer
  selector:
    app: xroad-cs
  ports:
    - port: 8081
      protocol: TCP
      name: client-https
{{- end }}